// Generates src/assets/theme.css (Tailwind v4 @theme) from ../design/tokens.json.
import { readFileSync, writeFileSync } from 'node:fs'

const tokens = JSON.parse(readFileSync(new URL('../../design/tokens.json', import.meta.url)))
const lines = ['/* AUTO-GENERATED by scripts/generate-theme.mjs from design/tokens.json. Do not edit. */', '@theme static {', '  --color-*: initial;']

// The design has no plain white token (it uses `surface`), but text on dark panels and solid badges is white.
lines.push('  --color-white: #FFFFFF;')
// A value like "{ink-muted}" is an alias of another color token (see design/DESIGN.md).
const colors = Object.fromEntries(tokens.color.tokens.map((t) => [t.name, t.value]))
const resolve = (value, seen = new Set()) => {
  const alias = /^\{(.+)\}$/.exec(value)
  if (!alias) return value
  const name = alias[1]
  if (!(name in colors) || seen.has(name)) throw new Error(`Cannot resolve color alias ${value}`)
  return resolve(colors[name], seen.add(name))
}
for (const t of tokens.color.tokens) lines.push(`  --color-${t.name}: ${resolve(t.value)};`)
for (const t of tokens.spacing.tokens) lines.push(`  --spacing-${t.name.replace('space-', 's')}: ${t.value};`)
for (const t of tokens.radius.tokens) lines.push(`  --radius-${t.name.replace('radius-', '')}: ${t.value};`)
lines.push(`  --font-sans: ${tokens.type.families.sans};`)
for (const s of tokens.type.groups.flatMap((g) => g.styles)) {
  lines.push(`  --text-${s.name}: ${s.fontSize};`)
  lines.push(`  --text-${s.name}--line-height: ${s.lineHeight};`)
  lines.push(`  --text-${s.name}--font-weight: ${s.fontWeight};`)
}
lines.push('}', '')
writeFileSync(new URL('../src/assets/theme.css', import.meta.url), lines.join('\n'))
console.log('theme.css generated')
