// Generates src/assets/theme.css (Tailwind v4 @theme) from ../design/tokens.json.
import { readFileSync, writeFileSync } from 'node:fs'

const tokens = JSON.parse(readFileSync(new URL('../../design/tokens.json', import.meta.url)))
const lines = ['/* AUTO-GENERATED by scripts/generate-theme.mjs from design/tokens.json. Do not edit. */', '@theme {', '  --color-*: initial;']

for (const t of tokens.color.tokens) lines.push(`  --color-${t.name}: ${t.value};`)
for (const t of tokens.spacing.tokens) lines.push(`  --spacing-${t.name.replace('space-', 's')}: ${t.value};`)
for (const t of tokens.radius.tokens) lines.push(`  --radius-${t.name.replace('radius-', '')}: ${t.value};`)
lines.push(`  --font-sans: ${tokens.type.families.sans};`)
for (const s of tokens.type.groups.flatMap((g) => g.styles)) {
  lines.push(`  --text-${s.name}: ${s.fontSize};`)
  lines.push(`  --text-${s.name}--line-height: ${s.lineHeight};`)
  lines.push(`  --text-${s.name}--font-weight: ${s.fontWeight};`)
}
lines.push('}', '')
writeFileSync(new URL('../src/assets/theme.css', import.meta.url), lines.join('\n'))
console.log('theme.css generated')
